### ISSUE TITLE
missing 2nd parameter

### ISSUE THREAD

**Issue by meghan452** [andygup/ionic2-esri-map#18]
Hey Andy, thanks for sharing this. I do want to let you know that there's one small change in the tab1 typescript file. @ViewChild requires 2 parameters, but the sample has only one

@ViewChild('map',{static: false}) mapEl!: ElementRef;

Once I added it, worked like a charm.

Once again thanks.

**Comment by andygup** [comment]
@meghan452 thanks, yep that's because this repo hasn't been updated in quite a while and represents an older version of Angular.

I should update the README. For the latest code there is another repo that demonstrates using Angular (latest) with esri-loader and webpack: https://github.com/Esri/angular-cli-esri-map
